//
// Created on 2026/4/23.
//
// Node APIs are not fully supported. To solve the compilation error of the interface cannot be found,
// please include "napi/native_api.h".

#ifndef PAL_OHOS_UI_DEFS_H
#define PAL_OHOS_UI_DEFS_H

#define CHUNKNUM_SPRITEUI 9
#define MENUITEM_COLOR 0x4F
#define MENUITEM_COLOR_INACTIVE 0x18
#define MENUITEM_COLOR_CONFIRMED 0x2C
#define MENUITEM_COLOR_SELECTED_TNACTIVE 0x1C
#define MENUITEM_COLOR_SELECTED_FIRST 0xF9
#define MENUITEM_COLOR_SELECTED_TOTALNUM 6

#define MENUITEM_COLOR_SELECTED                                                                                        \
    (MENUITEM_COLOR_SELECTED_FIRST +                                                                                   \
     SDLPal::SDL_GetTicks() / (600 / MENUITEM_COLOR_SELECTED_TOTALNUM) % MENUITEM_COLOR_SELECTED_TOTALNUM)

#define MENUITEM_COLOR_EQUIPPEDITEM 0xC8

#define DESCTEXT_COLOR 0x3C

/**
 * 源项目存在对操作系统的一层判断
 * 考虑到不存在类似的使用场景
 * 因此不再添加这层判断
 */
#define MAINMENU_BACKGROUND_FBPNUM 60

#define RIX_NUM_OPENINGMENU 4
#define MAINMENU_LABEL_NEWGAME 7
#define MAINMENU_LABEL_LOADGAME 8

#define LOADMENU_LABEL_SLOT_FIRST 43

#define CONFIRMMENU_LABEL_ON 19
#define CONFIRMMENU_LABEL_YES 20

#define CASH_LABEL 21

#define SWITCHMENU_LABEL_DISABLE 17
#define SWITCHMENU_LABEL_ENABLE 18

#define GAMEMENU_LABEL_STATUS 3
#define GAMEMENU_LABEL_MAGIC 4
#define GAMEMENU_LABEL_INVENTORY 5
#define GAMEMENU_LABEL_SYSTEM 6

#define SYSMENU_LABEL_SAVE 11
#define SYSMENU_LABEL_LOAD 12
#define SYSMENU_LABEL_MUSIC 13
#define SYSMENU_LABEL_SOUND 14
#define SYSMENU_LABEL_QUIT 15
#define SYSMENU_LABEL_BATTLEMODE 606
#define SYSMENU_LABEL_LAUNCHSETTING 612

#define BATTLESPEEDMENU_LABEL_1 (SYSMENU_LABEL_BATTLEMODE + 1)
#define BATTLESPEEDMENU_LABEL_2 (SYSMENU_LABEL_BATTLEMODE + 2)
#define BATTLESPEEDMENU_LABEL_3 (SYSMENU_LABEL_BATTLEMODE + 3)
#define BATTLESPEEDMENU_LABEL_4 (SYSMENU_LABEL_BATTLEMODE + 4)
#define BATTLESPEEDMENU_LABEL_5 (SYSMENU_LABEL_BATTLEMODE + 5)

#define INVMENU_LABEL_USE 23
#define INVMENU_LABEL_EQUIP 22

#define STATUS_BACKGROUND_FBPNUM 0
#define STATUS_LABEL_EXP 2
#define STATUS_LABEL_LEVEL 48
#define STATUS_LABEL_HP 49
#define STATUS_LABEL_MP 50
#define STATUS_LABEL_EXP_LAYOUT 29
#define STATUS_LABEL_LEVEL_LAYOUT 30
#define STATUS_LABEL_HP_LAYOUT 31
#define STATUS_LABEL_MP_LAYOUT 32
#define STATUS_LABEL_ATTACKPOWER 51
#define STATUS_LABEL_MAGICPOWER 52
#define STATUS_LABEL_RESISTANCE 53
#define STATUS_LABEL_DEXTERITY 54
#define STATUS_LABEL_FLEERATE 55
#define STATUS_COLOR_EQUIPMENT 0xBE

#define EQUIP_LABEL_HEAD 600
#define EQUIP_LABEL_SHOULDER 601
#define EQUIP_LABEL_BODY 602
#define EQUIP_LABEL_HAND 603
#define EQUIP_LABEL_FOOT 604
#define EQUIP_LABEL_NECK 605

#define BUYMENU_LABEL_CURRENT 35
#define SELLMENU_LABEL_PRICE 25

#define SPRITENUM_SLASH 39
#define SPRITENUM_ITEMBOX 70
#define SPRITENUM_CURSOR_YELLOW_UP 66
#define SPRITENUM_CURSOR_UP 67
#define SPRITENUM_CURSOR_YELLOW 68
#define SPRITENUM_CURSOR 69
#define SPRITENUM_PLAYERINFOBOX 18
#define SPRITENUM_PLAYERFACE_FIRST 48

#define EQUIPMENU_BACKGROUND_FBPNUM 1

#define ITEMUSEMENU_COLOR_STATLABEL 0xBB

#define BATTLEWIN_GETEXP_LABEL 30
#define BATTLEWIN_BEATENEMY_LABEL 9
#define BATTLEWIN_DOLLAR_LABEL 10
#define BATTLEWIN_LEVELUP_LABEL 32
#define BATTLEWIN_ADDMAGIC_LABEL 33
#define BATTLEWIN_LEVELUP_LABEL_COLOR 0xBB
#define SPRITENUM_ARROW 47

#define BATTLE_LABEL_ESCAPEFAIL 31

#endif // PAL_OHOS_UI_DEFS_H
